### ISSUE TITLE
output page options

### ISSUE THREAD

**Issue by muralikodali** [dragotin/pdfquirk#8] opened 2021-07-22 08:27 UTC
this is a simple to use and convenient program.

i have tried to convert some images. pdf output is good.

i request to add some options to make it more useful.

images are printed upto the margin of pdf file. if there are **options for controlling page margins** (top, bottom, left and right options ) and **page orientation** ( portrait or landscape ), output pdf will be more beautiful.

**Comment by dragotin** [comment] 2021-11-27 22:04
Done in the last few commits. Will be released soon as version 0.95.

**Comment by muralikodali** [comment] 2021-11-28 06:12
program is giving following error.

```
caught height 189
Copying file "/home/xxxx/Pictures/mmk_ppsize.jpg"
Copying to "18314222140a535998a4261e8afdb4de8270bc35"
Item  "Page 1" is selected: false
Item  "Page 1" is selected: false
Item  "Page 1" is selected: false
Item  "Page 1" is selected: false
Item  "Page 1" is selected: false
Item  "Page 1" is selected: false
stderr output:  "usage: img2pdf [-h] [-v] [-V] [--gui] [--from-file FILE] [-o out]\n               [-C colorspace] [-D] [--engine engine] [--first-frame-only]\n               [--pillow-limit-break] [--pdfa [PDFA]] [-S LxL] [-s LxL]\n               [-b L[:L]] [-f FIT] [-a] [-r ROT] [--crop-border L[:L]]\n               [--bleed-border L[:L]] [--trim-border L[:L]]\n               [--art-border L[:L]] [--title title] [--author author]\n               [--creator creator] [--producer producer]\n               [--creationdate creationdate] [--moddate moddate]\n               [--subject subject] [--keywords kw [kw ...]]\n               [--viewer-panes PANES] [--viewer-initial-page NUM]\n               [--viewer-magnification MAG] [--viewer-page-layout LAYOUT]\n               [--viewer-fit-window] [--viewer-center-window]\n               [--viewer-fullscreen]\n               [infile ...]\nimg2pdf: error: unrecognized arguments: --without-pdfrw\n"
```

**Comment by dragotin** [comment] 2021-12-01 07:51
Ok, this option was removed from more recent versions of img2pdf. Good. So hopefully/ probably the problem with transparent png files that I tried to solve with that option was solved as well. 

I'll remove that again in the code and would ask you to check again.

**Closed as completed** 2021-12-01 07:58 UTC

**Comment by muralikodali** [comment] 2021-12-01 16:18
thanks for the update.

the program is now working without error.

i request you to update the readme.md with scanner command line options, which otherwise will be difficult to find (the exact command) . i have found that scanimage info grepping the repository.

**Comment by dragotin** [comment] 2021-12-01 20:33
The problem is that the scanimage command line is different for each scanner. See http://www.sane-project.org/lj98/doc003.html for more information. Would that have helped you? In that case I will reference it.

**Comment by muralikodali** [comment] 2021-12-07 06:11
just give a suggestion like below : 

```
scanimage  --mode Color --resolution 150  -l 0 -t 0 -x 210 -y 297  --format=png
```
previously i have tried above command with output name also, as we do in bash scripts. it failed. 
now i have grepped the project and found the command to use.
there is a gap of one month between doing these things.

so, giving a help suggestion like the above one will help to try the software with ease.
